---
# yamllint disable rule:line-length

version: "3.4"
services:
  infrahub-server:
    build:
      context: ../
      dockerfile: development/Dockerfile
      target: backend
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    pull_policy: always
    command: >
      gunicorn --config backend/infrahub/serve/gunicorn_config.py --logger-class infrahub.serve.log.GunicornLogger infrahub.server:app
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=INFO"
      - "INFRAHUB_SECURITY_INITIAL_ADMIN_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec"
      - "INFRAHUB_SECURITY_SECRET_KEY=327f747f-efac-42be-9e73-999f08f86b92"
      - "INFRAHUB_ALLOW_ANONYMOUS_ACCESS=true"
      - "INFRAHUB_DB_TYPE=${INFRAHUB_DB_TYPE}"
    volumes:
      - "storage_data:/opt/infrahub/storage"
    tty: true
    healthcheck:
      test: wget -O /dev/null http://localhost:8000/api/schema/summary || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  infrahub-git:
    deploy:
      mode: replicated
      replicas: 2
    build:
      context: ../
      dockerfile: development/Dockerfile
      target: backend
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    pull_policy: always
    command: infrahub git-agent start --debug
    restart: unless-stopped
    depends_on:
      - infrahub-server
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_ADDRESS=http://infrahub-server:8000"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=DEBUG"
      - "INFRAHUB_SDK_API_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec"
      - "INFRAHUB_SDK_TIMEOUT=20"
      - "INFRAHUB_DB_TYPE=${INFRAHUB_DB_TYPE}"
    volumes:
      - "git_data:/opt/infrahub/git"
      - "git_remote_data:/remote"
    tty: true

volumes:
  git_data:
  git_remote_data:
  storage_data:
