---
# yamllint disable rule:line-length

version: "3.4"
services:
  infrahub-test:
    build:
      context: ../
      dockerfile: development/Dockerfile
      target: backend
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    environment:
      - "INFRAHUB_BUILD_NAME=${INFRAHUB_BUILD_NAME}"
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=CRITICAL"
      - "INFRAHUB_TEST_IN_DOCKER=1"
      - "INFRAHUB_DB_TYPE=${INFRAHUB_DB_TYPE}"
    volumes:
      - ../:/source
    tty: true
