[main]
internal_address = "http://infrahub-server:8000"

[git]
repositories_directory = "/opt/infrahub/git"

[database]
username = "neo4j"
password = "admin"
address = "database"
port = 7687
protocol = "bolt"

[broker]
address = "message-queue"
username = "infrahub"
password = "infrahub"

[cache]
address = "cache"

[storage]
driver = "local"
