---
# yamllint disable rule:truthy
name: github

on:
  push:
    branches:
      - "develop"
      - "stable"
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          # exclude: |
          #   help*
          #   *issue
