---
# yamllint disable rule:truthy
name: Release Note

on:
  workflow_dispatch:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop
      - stable
  # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_infrahub_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: infrahub-release-drafter.yml
          disable-autolabeler: true
          name: infrahub-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_infrahub_sdk_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: infrahub_sdk-release-drafter.yml
          disable-autolabeler: true
          name: infrahub_sdk-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
