---
# yamllint disable rule:truthy
name: Update Docker Compose on Pyproject update in Stable

# This will bump the infrahub docker image in the docker-compose.yml
# when pyproject.toml is change in the stable branch

on:
  push:
    branches:
      - stable
    paths:
      - 'pyproject.toml'
  pull_request:
    branches:
      - stable
    types:
      - closed

jobs:
  update-docker-compose:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'stable')


    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
        with:
          token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: "Setup environment"
        run: |
          pipx install poetry
          poetry config virtualenvs.prefer-active-python true
      - name: "Install Package"
        run: "poetry install --all-extras"

      - name: "Update Docker Env variable in docker-compose.yml file"
        run: "poetry run invoke dev.gen-config-env -u"
      - name: "Update Infrahub Image Version in docker-compose.yml file"
        run: "poetry run invoke dev.update-docker-compose"
      - name: Commit docker-compose.yml
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
          push-branch: 'stable'
          commit-message: 'chore: update docker-compose'
          files: |
            docker-compose.yml
          name: opsmill-bot
          email: github-bot@opsmill.com
          rebase: true
